"""
app/services/pdf_export.py — Export an evidence pack as a PDF for chargeback
dispute submission or internal fraud-review documentation.
"""
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_evidence_pdf(evidence: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("title", parent=styles["Heading1"], fontSize=16)
    elements = []

    elements.append(Paragraph(f"Evidence Pack — {evidence['order_id']}", title_style))
    elements.append(Spacer(1, 0.5*cm))

    band_color = {"Green": colors.green, "Yellow": colors.orange, "Red": colors.red}.get(
        evidence["band"], colors.black)

    summary_data = [
        ["Risk Score", f"{evidence['risk_score']}/100"],
        ["Band", evidence["band"]],
        ["Order Value", f"Rs {evidence['order_value']:,.2f}"],
        ["Category", evidence["category"]],
    ]
    summary_table = Table(summary_data, colWidths=[5*cm, 10*cm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
        ("TEXTCOLOR", (1, 1), (1, 1), band_color),
        ("FONTNAME", (1, 1), (1, 1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.7*cm))

    elements.append(Paragraph("Why this was flagged:", styles["Heading3"]))
    for reason in evidence["reasons"]:
        elements.append(Paragraph(f"&bull; {reason}", styles["Normal"]))
    elements.append(Spacer(1, 0.5*cm))

    elements.append(Paragraph("Recommended action:", styles["Heading3"]))
    elements.append(Paragraph(evidence["recommended_action"], styles["Normal"]))
    elements.append(Spacer(1, 0.5*cm))

    elements.append(Paragraph(
        "This document is generated by an automated defense-only risk system. "
        "It does not constitute a final fraud determination; a human reviewer "
        "must confirm any action taken on this account.",
        ParagraphStyle("disclaimer", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
    ))

    doc.build(elements)
    return buffer.getvalue()
